const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),$=s=>document.querySelector(s),W=1100,H=620,keys={};let running=false,last=0,energy=100,fragments=0,zone="ruins",dialogue=null,toastTimer=0;
const player={x:130,y:475,r:14,speed:190};
const zones={ruins:{name:"RUINES",bg:["#8d2432","#1a1019"],exit:{x:1035,y:120,w:35,h:390},npc:{x:230,y:470,name:"MARA"},items:[{x:430,y:410,t:"fragment"},{x:780,y:270,t:"shadow"},{x:900,y:500,t:"shadow"}]},station:{name:"STATION",bg:["#5d2632","#090b11"],exit:{x:40,y:100,w:35,h:420},items:[{x:270,y:250,t:"fragment"},{x:690,y:430,t:"shadow"},{x:860,y:180,t:"shadow"}]},shelter:{name:"ABRI",bg:["#40202c","#080a0f"],exit:null,items:[{x:520,y:300,t:"fragment"}]}};let items=[];
function reset(){energy=100;fragments=0;zone="ruins";player.x=130;player.y=475;dialogue=null;loadZone();updateHUD()}
function loadZone(){items=zones[zone].items.map((i,n)=>({...i,id:n,active:true,hit:0}))}
function updateHUD(){$("#energy").textContent=Math.max(0,Math.round(energy));$("#shards").textContent=fragments+" / 3";$("#zone").textContent=zones[zone].name;$("#objective").textContent=fragments<3?"Trouver les 3 fragments":"Atteindre l'abri"}
function say(s,t){dialogue={speaker:s,text:t};$("#speaker").textContent=s;$("#dialogueText").textContent=t;$("#dialogue").classList.remove("hidden")}
function closeDialogue(){dialogue=null;$("#dialogue").classList.add("hidden")}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");toastTimer=1.3}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function move(dt){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){let l=Math.hypot(dx,dy);player.x+=dx/l*player.speed*dt;player.y+=dy/l*player.speed*dt;energy-=2.1*dt}player.x=Math.max(35,Math.min(W-35,player.x));player.y=Math.max(70,Math.min(H-55,player.y))}
function interact(){if(dialogue){closeDialogue();return}let z=zones[zone];if(z.npc&&dist(player,z.npc)<65){say("MARA","Le ciel rouge efface les souvenirs. Trouve les trois fragments de mémoire. L'abri est à l'est.");return}for(let i of items)if(i.active&&i.t==="fragment"&&Math.hypot(player.x-i.x,player.y-i.y)<45){i.active=false;fragments++;energy=Math.min(100,energy+20);toast("+ FRAGMENT DE MÉMOIRE");updateHUD();return}}
function lamp(){energy=Math.max(0,energy-6);for(let i of items)if(i.active&&i.t==="shadow"&&Math.hypot(player.x-i.x,player.y-i.y)<115){i.active=false;toast("OMBRE REPOUSSÉE")}}
function transition(){let z=zones[zone];if(!z.exit)return;if(player.x>z.exit.x&&player.y>z.exit.y&&player.y<z.exit.y+z.exit.h){if(zone==="ruins"){zone="station";player.x=75;player.y=310;loadZone();toast("STATION ABANDONNÉE")}else if(zone==="station"&&fragments>=3){zone="shelter";player.x=1000;player.y=310;loadZone();toast("ABRI")}else if(zone==="station"){toast("PORTE VERROUILLÉE : 3 FRAGMENTS");player.x=70}}}
function enemies(dt){for(let i of items)if(i.active&&i.t==="shadow"){let d=Math.hypot(player.x-i.x,player.y-i.y);if(d<190){i.x+=(player.x-i.x)/Math.max(d,1)*32*dt;i.y+=(player.y-i.y)/Math.max(d,1)*32*dt}if(d<28&&performance.now()>i.hit){energy-=16;i.hit=performance.now()+850;toast("L'OMBRE TE TOUCHE")}}}
function win(){if(zone==="shelter"&&fragments>=3&&player.x>900){running=false;$("#gameover").classList.remove("hidden");$("#endTitle").textContent="La dernière lueur survit.";$("#endText").textContent="Les trois fragments sont réunis. Tu as atteint l'abri."}}
function draw(){let z=zones[zone],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,z.bg[0]);g.addColorStop(.58,"#21131d");g.addColorStop(1,z.bg[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#ffb36b";ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(870,130,72,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#20151e";for(let i=0;i<9;i++){let x=i*145-30,h=90+(i%4)*35;ctx.fillRect(x,H-115-h,95,h)}ctx.fillStyle="#0b0b10";ctx.fillRect(0,H-115,W,115);if(z.exit){ctx.strokeStyle="#ff765c";ctx.setLineDash([8,7]);ctx.strokeRect(z.exit.x,z.exit.y,z.exit.w,z.exit.h);ctx.setLineDash([])}if(zone==="ruins"){ctx.fillStyle="#ff8a6a";ctx.font="16px system-ui";ctx.fillText("MARA",205,442)}for(let i of items)if(i.active){if(i.t==="fragment"){ctx.save();ctx.translate(i.x,i.y);ctx.rotate(Math.PI/4);ctx.fillStyle="#9ffcff";ctx.shadowColor="#63efff";ctx.shadowBlur=22;ctx.fillRect(-10,-10,20,20);ctx.restore()}else{ctx.fillStyle="#120b15";ctx.strokeStyle="#db4861";ctx.lineWidth=2;ctx.beginPath();ctx.arc(i.x,i.y,13,0,Math.PI*2);ctx.fill();ctx.stroke()}}ctx.fillStyle="#e8d7c8";ctx.shadowColor="#ffd7a0";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function tick(t){if(!running)return;let dt=Math.min(.033,(t-last)/1000||.016);last=t;if(!dialogue)move(dt);enemies(dt);transition();win();if(energy<=0){running=false;$("#gameover").classList.remove("hidden");$("#endTitle").textContent="La nuit est tombée.";$("#endText").textContent="Tu as récupéré "+fragments+" fragment(s)."}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$("#toast").classList.remove("show")}draw();updateHUD();requestAnimationFrame(tick)}
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key===" "){e.preventDefault();if(dialogue)closeDialogue();else lamp()}if(e.key.toLowerCase()==="e")interact();if(e.key.toLowerCase()==="r"){reset();$("#intro").classList.add("hidden");$("#gameover").classList.add("hidden");running=true;last=performance.now();requestAnimationFrame(tick)}});addEventListener("keyup",e=>keys[e.key]=false);$("#start").onclick=()=>{$("#intro").classList.add("hidden");reset();running=true;last=performance.now();requestAnimationFrame(tick)};$("#restart").onclick=()=>{$("#gameover").classList.add("hidden");reset();running=true;last=performance.now();requestAnimationFrame(tick)};draw();